#! /bin/bash

echo "[Initial Server Setup]"
echo "Installing the following tools: vim, python-pip"

sudo apt-get install vim, python-pip

echo "[Django setup] Installing django"
pip install --upgrade Django
